name: ML Workflow

on:
  push:
    branches:
      - kernelridge

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dtree/requirements.txt

      - name: Run Decision Tree training
        run: |
          python dtree/train.py

      - name: Run Kernel Ridge training
        run: |
          python kernelridge/train2.py
